### ISSUE TITLE
X, y are not equal

### ISSUE THREAD

**Issue by furqan915** [christina-bohk-ewald/demographic-scaling-model#1]
Hello,

Thank you for sharing this really great work.
I am working on this code as I also want to estimate the COVID19 prevalence.
I am facing a problem in step-2-infections-map-ifr-thanatAge-ageSpecific-deaths.R
Here at the section: 2. Ungroup remaining life years (ex) & map reference countries' infection fatality rate via thanatological age, whenever I am running the function
```
mapped_mode_ifr_thanatAge <- map_fr_betw_ref_and_coi_thanatAge(deaths=deaths,
						lt_1950_2020=lt_1950_2020,
						ungrouped_cfr_by_single_age_china_sp=ungrouped_mode_ifr_by_single_age_china_sp)

```
I am getting this error
`Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ `

I can understand that both values are not equal. But how to resolve this issue that is the query?
Kindly respond to this.
Thanks

**Comment by christina-bohk-ewald** [comment]
Hi,

Thank you for your interest in the demographic scaling model. Unfortunately, I do not have enough details to tell you exactly what is going wrong, beyond the fact that the data format of input variables appear to not match (-> as you already suspect). However, I would like to recommend to go through this tutorial that I have created for my teaching: https://github.com/christina-bohk-ewald/2020-COS-D407-scientific-modeling-and-model-validation/blob/master/week-3/2020-COS-D407-hands-on-exercise-week-3.pdf It is open and freely available on GitHub and it walks you through the application of the demographic scaling model step by step. I hope that this will help to solve your issue. 

Best wishes
